name: Pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@c00625b5f30db226fb0634299effc4cd15fdd7bb # v17.2.0
        with:
          auto-commit: "true"
